# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Brick' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'
  pod 'SDWebImage'
  pod 'ReactiveCocoa', '~> 4.2.1'
  pod 'YTKNetwork'
  
    target 'BrickTests' do
        pod 'OCMock'
    end

end
