
# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'BrickKit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

    pod 'Masonry'
    pod 'SDWebImage'
    pod 'ReactiveCocoa'
    
  target 'BrickKitTests' do
      pod 'OCMock'
  end

  target 'BrickKitUITests' do
    
  end

end